name: reuseable workflow
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      expose_var:
        description: "test var"
        value: ${{ jobs.activate-github-runner.outputs.expose_var }}
    inputs:
      passed-var:
        type: string
        required: true
        
jobs:
  activate-github-runner:
    runs-on: ubuntu-latest
    outputs:
      expose_var: "test-var"
    steps:
      - name: TEST 
        run : echo "Hello world! ${{inputs.passed-var}}"
